<a href="https://colab.research.google.com/github/Mrudhula1/ICP_3/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem - 1


In [5]:
class Employee:
    num_Of_Employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_Of_Employees+=1


def avg_salary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.num_Of_Employees)
list_of_Employees = [employee1, employee2]
average_salary = avg_salary(listofEmployees)
print("Avg salary is :", average_salary)




Employee 1: 
Enter name: Mrudhula
Family Members: soumith
Employee Salary: 3000
Employee Department: development
Employee 2: 
Enter name: meghana
Family Members: srikar
Employee Salary: 4000
Employee Department: devops
Full Time Employee 1: 
Enter name: srikar
Family Members: meghana
Employee Salary: 5000
Employee Department: development

Number of employees:  3
Avg salary is : 4750.0


Problem - 2


In [6]:
import numpy

ran_vec = numpy.random.uniform(1, 20, 20)
print(ran_vec)
print("")
print("")
reshaped_arr = ran_vec.reshape(4, 5)
print("")
print("")
print(reshaped_arr)
reshaped_arr[numpy.arange(4), numpy.argmax(reshaped_arr, axis=1)] = 0
print("")
print("")
print(reshaped_arr)

[ 2.91816038  2.65496856  8.89675818 19.07694936 15.62863403 16.49238676
 13.16196185  3.58886645  1.6807913  13.82595764  5.73908893 10.73728414
 19.55660948 13.36102511 19.27794566 12.83885982 19.30659768 14.52836927
 10.40373727  9.66765826]




[[ 2.91816038  2.65496856  8.89675818 19.07694936 15.62863403]
 [16.49238676 13.16196185  3.58886645  1.6807913  13.82595764]
 [ 5.73908893 10.73728414 19.55660948 13.36102511 19.27794566]
 [12.83885982 19.30659768 14.52836927 10.40373727  9.66765826]]


[[ 2.91816038  2.65496856  8.89675818  0.         15.62863403]
 [ 0.         13.16196185  3.58886645  1.6807913  13.82595764]
 [ 5.73908893 10.73728414  0.         13.36102511 19.27794566]
 [12.83885982  0.         14.52836927 10.40373727  9.66765826]]
